import { addDays, makeId } from "@/lib/format";
import { Item, Plan, ProjectConfig, Settings, SubProfile } from "@/types/models";

/**
 * Seed photos use a `seed://` scheme rendered as a labelled colour block so the
 * app feels alive on first open without depending on the network.
 */
function seedPhoto(label: string, tone: string): string {
  return `seed://${tone}/${encodeURIComponent(label)}`;
}

function daysAgo(n: number): string {
  const d = new Date();
  d.setDate(d.getDate() - n);
  return d.toISOString();
}

const DEFAULT_PROJECT_CONFIG = (name: string): ProjectConfig => ({
  name,
  address: "",
  buildings: ["Block A", "Block B"],
  levels: ["L01", "L02", "L03"],
  units: [],
  rooms: [
    "Kitchen",
    "Living",
    "Bathroom",
    "Ensuite",
    "Bedroom 1",
    "Bedroom 2",
    "Laundry",
    "Balcony",
    "Hallway",
    "Garage",
  ],
  defaultDueDays: 7,
});

const DEFAULT_SUBS = [
  "Coastline Painting",
  "Apex Plastering",
  "Sterling Tiling",
  "AquaSeal Waterproofing",
  "TrueLine Joinery",
  "Northline Electrical",
  "Pacific Plumbing",
  "Skyline Glazing",
  "Premier Flooring",
  "Endeavour Cleaning",
];

function tradeGuess(name: string): string | undefined {
  const m = name.toLowerCase();
  if (m.includes("paint")) return "Painting";
  if (m.includes("plaster")) return "Plastering";
  if (m.includes("til")) return "Tiling";
  if (m.includes("water") || m.includes("seal")) return "Waterproofing";
  if (m.includes("joinery")) return "Joinery";
  if (m.includes("electric")) return "Electrical";
  if (m.includes("plumb") || m.includes("hydra")) return "Hydraulic";
  if (m.includes("glaz") || m.includes("window")) return "Windows / Aluminium";
  if (m.includes("floor")) return "Flooring";
  if (m.includes("clean")) return "Cleaning";
  return undefined;
}

const DEFAULT_SUB_PROFILES: Record<string, SubProfile> = Object.fromEntries(
  DEFAULT_SUBS.map((name) => [
    name,
    {
      name,
      trade: tradeGuess(name),
      contact: "Site Contact",
      email: `${name.toLowerCase().replace(/[^a-z]+/g, "")}@example.com`,
      phone: "0400 000 000",
    } satisfies SubProfile,
  ]),
);

export function buildDemoSettings(): Settings {
  return {
    projects: ["Jura Noosa", "Meta Street"],
    projectConfigs: {
      "Jura Noosa": {
        ...DEFAULT_PROJECT_CONFIG("Jura Noosa"),
        address: "Jura · Noosa Heads QLD",
        buildings: ["Block A", "Block B"],
        levels: ["L01", "L02", "L03"],
        units: ["A-304", "A-305", "B-112", "B-204"],
      },
      "Meta Street": {
        ...DEFAULT_PROJECT_CONFIG("Meta Street"),
        address: "Meta Street · Mooloolaba QLD",
        buildings: ["Tower 1"],
        levels: ["L01", "L02", "L05", "L08", "L10"],
        units: ["T1-502", "T1-803", "T1-1004"],
      },
    },
    subcontractors: [...DEFAULT_SUBS].sort((a, b) => a.localeCompare(b)),
    subProfiles: DEFAULT_SUB_PROFILES,
    activeProject: "Jura Noosa",
    company: "CleanRun Construction",
    preparedBy: "Site Manager",
  };
}

function base(partial: Partial<Item> & Pick<Item, "id" | "code" | "type" | "status">): Item {
  const now = daysAgo(0);
  return {
    project: "Jura Noosa",
    building: "Block A",
    level: "L03",
    unit: "A-304",
    room: "Bathroom",
    trade: "Tiling",
    subcontractor: "Sterling Tiling",
    priority: "high",
    dueDate: addDays(3),
    description: "",
    createdAt: now,
    updatedAt: now,
    createdBy: "Site Manager",
    originalPhotos: [],
    rectificationEvidence: [],
    closeoutEvidence: [],
    comments: [],
    issueHistory: [],
    inspectionHistory: [],
    auditEvents: [{ at: now, action: `Created (${partial.code})`, by: "Site Manager" }],
    sync: "synced",
    ...partial,
  };
}

export function buildDemoItems(): Item[] {
  return [
    base({
      id: "demo-def-open-jura",
      code: "DEF-001",
      type: "defect",
      status: "open",
      building: "Block B",
      level: "L02",
      unit: "B-204",
      room: "Bathroom",
      trade: "Tiling",
      subcontractor: "Sterling Tiling",
      priority: "high",
      dueDate: addDays(2),
      description: "Cracked floor tile beside vanity unit. Chip on adjacent skirting tile.",
      originalPhotos: [seedPhoto("Cracked tile", "amber"), seedPhoto("Skirting chip", "amber")],
      createdAt: daysAgo(1),
      auditEvents: [{ at: daysAgo(1), action: "Created (DEF-001)", by: "Site Manager" }],
    }),
    base({
      id: "demo-def-issued-jura",
      code: "DEF-002",
      type: "defect",
      status: "issued",
      building: "Block A",
      level: "L03",
      unit: "A-305",
      room: "Ensuite",
      trade: "Waterproofing",
      subcontractor: "AquaSeal Waterproofing",
      priority: "urgent",
      dueDate: addDays(1),
      description: "Active moisture behind shower wall — membrane suspected compromised.",
      originalPhotos: [seedPhoto("Moisture stain", "red")],
      issuedAt: daysAgo(2),
      issueHistory: [{ at: daysAgo(2), to: "AquaSeal Waterproofing", by: "Site Manager" }],
      auditEvents: [
        { at: daysAgo(3), action: "Created (DEF-002)", by: "Site Manager" },
        { at: daysAgo(2), action: "Issued to AquaSeal Waterproofing", by: "Site Manager" },
      ],
    }),
    base({
      id: "demo-def-inprogress-meta",
      code: "DEF-003",
      type: "defect",
      status: "in_progress",
      project: "Meta Street",
      building: "Tower 1",
      level: "L05",
      unit: "T1-502",
      room: "Kitchen",
      trade: "Tiling",
      subcontractor: "Sterling Tiling",
      priority: "high",
      dueDate: addDays(4),
      description: "Lippage on splashback tiles exceeds tolerance near rangehood.",
      originalPhotos: [seedPhoto("Tile lippage", "amber")],
      issuedAt: daysAgo(6),
      inProgressAt: daysAgo(3),
      issueHistory: [{ at: daysAgo(6), to: "Sterling Tiling", by: "Site Manager" }],
      rectificationEvidence: [
        {
          id: makeId(),
          comment: "Removed three tiles, re-screeding bed today. Photos to follow.",
          by: "Sterling Tiling",
          at: daysAgo(2),
        },
      ],
      auditEvents: [
        { at: daysAgo(7), action: "Created (DEF-003)", by: "Site Manager" },
        { at: daysAgo(6), action: "Issued to Sterling Tiling", by: "Site Manager" },
        { at: daysAgo(3), action: "Marked in progress", by: "Sterling Tiling" },
        { at: daysAgo(2), action: "Rectification evidence added", by: "Sterling Tiling" },
      ],
    }),
    base({
      id: "demo-def-ready-jura",
      code: "DEF-004",
      type: "defect",
      status: "ready_for_review",
      building: "Block A",
      level: "L03",
      unit: "A-304",
      room: "Bathroom",
      trade: "Tiling",
      subcontractor: "Sterling Tiling",
      priority: "high",
      dueDate: addDays(1),
      description: "Grout discolouration along bath hob, re-grout required.",
      originalPhotos: [seedPhoto("Grout staining", "amber")],
      issuedAt: daysAgo(8),
      inProgressAt: daysAgo(5),
      readyForReviewAt: daysAgo(1),
      issueHistory: [{ at: daysAgo(8), to: "Sterling Tiling", by: "Site Manager" }],
      rectificationEvidence: [
        {
          id: makeId(),
          photo: seedPhoto("Re-grouted hob", "green"),
          comment: "Re-grouted full hob and cleaned down. Ready for review.",
          by: "Sterling Tiling",
          at: daysAgo(1),
        },
      ],
      auditEvents: [
        { at: daysAgo(9), action: "Created (DEF-004)", by: "Site Manager" },
        { at: daysAgo(8), action: "Issued to Sterling Tiling", by: "Site Manager" },
        { at: daysAgo(5), action: "Marked in progress", by: "Sterling Tiling" },
        { at: daysAgo(1), action: "Rectification evidence added", by: "Sterling Tiling" },
        { at: daysAgo(1), action: "Marked ready for review", by: "Sterling Tiling" },
      ],
    }),
    base({
      id: "demo-def-inspection-meta",
      code: "DEF-005",
      type: "defect",
      status: "under_inspection",
      project: "Meta Street",
      building: "Tower 1",
      level: "L08",
      unit: "T1-803",
      room: "Living",
      trade: "Windows / Aluminium",
      subcontractor: "Skyline Glazing",
      priority: "high",
      dueDate: addDays(0),
      description: "Scratch on living room window glass, full pane replacement.",
      originalPhotos: [seedPhoto("Scratched glass", "amber")],
      issuedAt: daysAgo(10),
      inProgressAt: daysAgo(7),
      readyForReviewAt: daysAgo(2),
      underInspectionAt: daysAgo(0),
      issueHistory: [{ at: daysAgo(10), to: "Skyline Glazing", by: "Site Manager" }],
      rectificationEvidence: [
        {
          id: makeId(),
          photo: seedPhoto("New pane fitted", "green"),
          comment: "Pane replaced and beads refitted.",
          by: "Skyline Glazing",
          at: daysAgo(2),
        },
      ],
      inspectionHistory: [{ at: daysAgo(0), by: "Site Manager", action: "started" }],
      auditEvents: [
        { at: daysAgo(11), action: "Created (DEF-005)", by: "Site Manager" },
        { at: daysAgo(10), action: "Issued to Skyline Glazing", by: "Site Manager" },
        { at: daysAgo(7), action: "Marked in progress", by: "Skyline Glazing" },
        { at: daysAgo(2), action: "Rectification evidence added", by: "Skyline Glazing" },
        { at: daysAgo(2), action: "Marked ready for review", by: "Skyline Glazing" },
        { at: daysAgo(0), action: "Inspection started", by: "Site Manager" },
      ],
    }),
    base({
      id: "demo-def-rejected-jura",
      code: "DEF-006",
      type: "defect",
      status: "rejected",
      building: "Block B",
      level: "L01",
      unit: "B-112",
      room: "Ensuite",
      trade: "Tiling",
      subcontractor: "Sterling Tiling",
      priority: "urgent",
      dueDate: addDays(-1),
      description: "Hollow tiles to ensuite floor, multiple drummy areas.",
      originalPhotos: [seedPhoto("Drummy tiles", "red")],
      issuedAt: daysAgo(12),
      inProgressAt: daysAgo(9),
      readyForReviewAt: daysAgo(4),
      rejectionReason: "Two tiles still drummy near drain. Re-fix and re-present.",
      issueHistory: [{ at: daysAgo(12), to: "Sterling Tiling", by: "Site Manager" }],
      rectificationEvidence: [
        {
          id: makeId(),
          photo: seedPhoto("Re-fixed tiles", "amber"),
          comment: "Re-fixed two tiles.",
          by: "Sterling Tiling",
          at: daysAgo(4),
        },
      ],
      inspectionHistory: [
        { at: daysAgo(3), by: "Site Manager", action: "started" },
        {
          at: daysAgo(3),
          by: "Site Manager",
          action: "rejected",
          reason: "Two tiles still drummy near drain. Re-fix and re-present.",
        },
      ],
      auditEvents: [
        { at: daysAgo(13), action: "Created (DEF-006)", by: "Site Manager" },
        { at: daysAgo(12), action: "Issued to Sterling Tiling", by: "Site Manager" },
        { at: daysAgo(9), action: "Marked in progress", by: "Sterling Tiling" },
        { at: daysAgo(4), action: "Rectification evidence added", by: "Sterling Tiling" },
        { at: daysAgo(3), action: "Rejected on inspection", by: "Site Manager" },
      ],
    }),
    base({
      id: "demo-def-closed-jura",
      code: "DEF-007",
      type: "defect",
      status: "closed",
      building: "Block A",
      level: "L03",
      unit: "A-304",
      room: "Kitchen",
      trade: "Painting",
      subcontractor: "Coastline Painting",
      priority: "high",
      dueDate: addDays(-2),
      description: "Paint scuff and roller marks to kitchen feature wall.",
      originalPhotos: [seedPhoto("Roller marks", "amber")],
      issuedAt: daysAgo(15),
      inProgressAt: daysAgo(12),
      readyForReviewAt: daysAgo(6),
      underInspectionAt: daysAgo(3),
      closedAt: daysAgo(2),
      issueHistory: [{ at: daysAgo(15), to: "Coastline Painting", by: "Site Manager" }],
      rectificationEvidence: [
        {
          id: makeId(),
          photo: seedPhoto("Repainted wall", "green"),
          comment: "Cut in and rolled two coats. Wall consistent.",
          by: "Coastline Painting",
          at: daysAgo(6),
        },
      ],
      inspectionHistory: [
        { at: daysAgo(3), by: "Site Manager", action: "started" },
        { at: daysAgo(2), by: "Site Manager", action: "accepted" },
      ],
      closeoutEvidence: [
        {
          id: makeId(),
          photo: seedPhoto("Closeout — wall", "green"),
          by: "Site Manager",
          role: "Site Manager",
          note: "Finish accepted. No marks under flood light.",
          confirmation: "Confirmed rectified",
          at: daysAgo(2),
        },
      ],
      auditEvents: [
        { at: daysAgo(16), action: "Created (DEF-007)", by: "Site Manager" },
        { at: daysAgo(15), action: "Issued to Coastline Painting", by: "Site Manager" },
        { at: daysAgo(12), action: "Marked in progress", by: "Coastline Painting" },
        { at: daysAgo(6), action: "Marked ready for review", by: "Coastline Painting" },
        { at: daysAgo(3), action: "Inspection started", by: "Site Manager" },
        { at: daysAgo(2), action: "Closed with evidence", by: "Site Manager" },
      ],
    }),
    base({
      id: "demo-inc-open-jura",
      code: "INC-001",
      type: "incomplete",
      status: "open",
      building: "Block A",
      level: "L03",
      unit: "A-305",
      room: "Laundry",
      trade: "Joinery",
      subcontractor: "TrueLine Joinery",
      priority: "high",
      dueDate: addDays(5),
      description: "Laundry overhead cabinet doors not yet hung. Hinges on site.",
      originalPhotos: [seedPhoto("Missing doors", "sky")],
      auditEvents: [{ at: daysAgo(1), action: "Created (INC-001)", by: "Site Manager" }],
    }),
    base({
      id: "demo-inc-complete-meta",
      code: "INC-002",
      type: "incomplete",
      status: "complete",
      project: "Meta Street",
      building: "Tower 1",
      level: "L10",
      unit: "T1-1004",
      room: "Bedroom 1",
      trade: "Flooring",
      subcontractor: "Premier Flooring",
      priority: "high",
      dueDate: addDays(-3),
      description: "Carpet edge trim to bedroom doorway not installed.",
      originalPhotos: [],
      issuedAt: daysAgo(9),
      inProgressAt: daysAgo(6),
      readyForReviewAt: daysAgo(3),
      closedAt: daysAgo(2),
      issueHistory: [{ at: daysAgo(9), to: "Premier Flooring", by: "Site Manager" }],
      auditEvents: [
        { at: daysAgo(10), action: "Created (INC-002)", by: "Site Manager" },
        { at: daysAgo(9), action: "Issued to Premier Flooring", by: "Site Manager" },
        { at: daysAgo(6), action: "Marked in progress", by: "Premier Flooring" },
        { at: daysAgo(2), action: "Completed (no photo required)", by: "Site Manager" },
      ],
    }),
    base({
      id: "demo-inc-complete-jura",
      code: "INC-003",
      type: "incomplete",
      status: "complete",
      building: "Block B",
      level: "L02",
      unit: "B-204",
      room: "Living",
      trade: "Electrical",
      subcontractor: "Northline Electrical",
      priority: "high",
      dueDate: addDays(-1),
      description: "Two GPO face plates pending in living area.",
      originalPhotos: [],
      issuedAt: daysAgo(7),
      inProgressAt: daysAgo(5),
      closedAt: daysAgo(1),
      issueHistory: [{ at: daysAgo(7), to: "Northline Electrical", by: "Site Manager" }],
      auditEvents: [
        { at: daysAgo(8), action: "Created (INC-003)", by: "Site Manager" },
        { at: daysAgo(7), action: "Issued to Northline Electrical", by: "Site Manager" },
        { at: daysAgo(1), action: "Completed (no photo required)", by: "Site Manager" },
      ],
    }),
    base({
      id: "demo-cld-ready-meta",
      code: "CLD-001",
      type: "client",
      status: "ready_for_review",
      project: "Meta Street",
      building: "Tower 1",
      level: "L02",
      unit: "T1-502",
      room: "Balcony",
      trade: "Cleaning",
      subcontractor: "Endeavour Cleaning",
      priority: "high",
      dueDate: addDays(1),
      raisedBy: "Superintendent",
      description: "Superintendent flagged paint overspray on balcony glass balustrade.",
      originalPhotos: [seedPhoto("Overspray", "violet")],
      issuedAt: daysAgo(5),
      inProgressAt: daysAgo(3),
      readyForReviewAt: daysAgo(1),
      issueHistory: [{ at: daysAgo(5), to: "Endeavour Cleaning", by: "Site Manager" }],
      rectificationEvidence: [
        {
          id: makeId(),
          photo: seedPhoto("Glass cleaned", "green"),
          comment: "Razor-cleaned and polished balustrade glass.",
          by: "Endeavour Cleaning",
          at: daysAgo(1),
        },
      ],
      auditEvents: [
        { at: daysAgo(6), action: "Created (CLD-001)", by: "Site Manager" },
        { at: daysAgo(5), action: "Issued to Endeavour Cleaning", by: "Site Manager" },
        { at: daysAgo(3), action: "Marked in progress", by: "Endeavour Cleaning" },
        { at: daysAgo(1), action: "Marked ready for review", by: "Endeavour Cleaning" },
      ],
    }),
    base({
      id: "demo-cld-closed-meta",
      code: "CLD-002",
      type: "client",
      status: "closed",
      project: "Meta Street",
      building: "Tower 1",
      level: "L05",
      unit: "T1-502",
      room: "Bathroom",
      trade: "Hydraulic",
      subcontractor: "Pacific Plumbing",
      priority: "urgent",
      dueDate: addDays(-4),
      raisedBy: "Client PM",
      description: "Client PM raised slow-draining basin in main bathroom.",
      originalPhotos: [seedPhoto("Slow drain", "violet")],
      issuedAt: daysAgo(14),
      inProgressAt: daysAgo(11),
      readyForReviewAt: daysAgo(7),
      underInspectionAt: daysAgo(5),
      closedAt: daysAgo(4),
      issueHistory: [{ at: daysAgo(14), to: "Pacific Plumbing", by: "Site Manager" }],
      rectificationEvidence: [
        {
          id: makeId(),
          photo: seedPhoto("Cleared trap", "green"),
          comment: "Cleared trap, re-tested flow. Draining freely.",
          by: "Pacific Plumbing",
          at: daysAgo(7),
        },
      ],
      inspectionHistory: [
        { at: daysAgo(5), by: "Site Manager", action: "started" },
        { at: daysAgo(4), by: "Site Manager", action: "accepted" },
      ],
      closeoutEvidence: [
        {
          id: makeId(),
          photo: seedPhoto("Closeout — basin", "green"),
          by: "Site Manager",
          role: "Site Manager",
          note: "Flow tested in front of client PM. Accepted.",
          confirmation: "Confirmed rectified",
          at: daysAgo(4),
        },
      ],
      auditEvents: [
        { at: daysAgo(15), action: "Created (CLD-002)", by: "Site Manager" },
        { at: daysAgo(14), action: "Issued to Pacific Plumbing", by: "Site Manager" },
        { at: daysAgo(11), action: "Marked in progress", by: "Pacific Plumbing" },
        { at: daysAgo(7), action: "Marked ready for review", by: "Pacific Plumbing" },
        { at: daysAgo(5), action: "Inspection started", by: "Site Manager" },
        { at: daysAgo(4), action: "Closed with evidence", by: "Site Manager" },
      ],
    }),
    base({
      id: "demo-def-voice-jura",
      code: "DEF-008",
      type: "defect",
      status: "open",
      building: "Block B",
      level: "L02",
      unit: "B-204",
      room: "Bathroom",
      trade: "Tiling",
      subcontractor: "Sterling Tiling",
      priority: "high",
      dueDate: addDays(4),
      description: "Damaged tile beside vanity in Block B level two, unit B-204 bathroom.",
      voiceTranscript:
        "Block B, level two, unit B-204 bathroom. Damaged tile beside vanity. Assign to Sterling Tiling. Medium priority. Due Friday.",
      originalPhotos: [seedPhoto("Damaged tile", "amber")],
      auditEvents: [
        { at: daysAgo(0), action: "Created (DEF-008) via Voice-to-Note", by: "Site Manager" },
      ],
    }),
    base({
      id: "demo-def-issued-meta",
      code: "DEF-009",
      type: "defect",
      status: "issued",
      project: "Meta Street",
      building: "Tower 1",
      level: "L01",
      unit: "T1-502",
      room: "Hallway",
      trade: "Plastering",
      subcontractor: "Apex Plastering",
      priority: "high",
      dueDate: addDays(3),
      description: "Cornice crack to hallway ceiling, approx 600mm.",
      originalPhotos: [seedPhoto("Cornice crack", "amber")],
      issuedAt: daysAgo(1),
      issueHistory: [{ at: daysAgo(1), to: "Apex Plastering", by: "Site Manager" }],
      auditEvents: [
        { at: daysAgo(2), action: "Created (DEF-009)", by: "Site Manager" },
        { at: daysAgo(1), action: "Issued to Apex Plastering", by: "Site Manager" },
      ],
    }),
  ];
}

export function buildDemoPlans(): Plan[] {
  return [
    {
      id: "demo-plan-jura-a-l03",
      project: "Jura Noosa",
      building: "Block A",
      level: "L03",
      name: "Block A · Level 3 floor plan",
      image: "seed-plan://jura-a-l03",
      createdAt: daysAgo(2),
      pins: [
        { id: "pin-1", x: 0.7, y: 0.34, itemId: "demo-def-ready-jura", label: "DEF-004" },
        { id: "pin-2", x: 0.32, y: 0.46, itemId: "demo-def-closed-jura", label: "DEF-007" },
        { id: "pin-3", x: 0.5, y: 0.7, itemId: "demo-inc-open-jura", label: "INC-001" },
      ],
    },
  ];
}
