from __future__ import annotations

from typing import Any, Protocol

from app.models import (
    AccessRequest,
    AppData,
    CloseoutEvidence,
    Comment,
    Item,
    ItemCreate,
    ItemUpdate,
    RectificationEvidence,
    Settings,
)


class CleanRunRepository(Protocol):
    def snapshot(self) -> AppData: ...

    def list_items(self, project: str | None = None, status: str | None = None) -> list[Item]: ...

    def get_item(self, item_id: str) -> Item: ...

    def create_item(self, payload: ItemCreate, *, issue_now: bool = False, actor: dict[str, Any] | None = None) -> Item: ...

    def update_item(self, item_id: str, payload: ItemUpdate, *, by: str | None = None, actor: dict[str, Any] | None = None) -> Item: ...

    def issue_item(self, item_id: str, *, to: str, by: str | None = None, note: str | None = None, reissue: bool = False, actor: dict[str, Any] | None = None) -> Item: ...

    def mark_in_progress(self, item_id: str, *, by: str | None = None, actor: dict[str, Any] | None = None) -> Item: ...

    def mark_ready(self, item_id: str, *, by: str | None = None, actor: dict[str, Any] | None = None) -> Item: ...

    def start_inspection(self, item_id: str, *, by: str, actor: dict[str, Any] | None = None) -> Item: ...

    def reject(self, item_id: str, *, by: str, reason: str, actor: dict[str, Any] | None = None) -> Item: ...

    def close_with_evidence(self, item_id: str, evidence: CloseoutEvidence, *, actor: dict[str, Any] | None = None) -> Item: ...

    def add_rectification(self, item_id: str, evidence: RectificationEvidence, *, advance_to_ready: bool = False, actor: dict[str, Any] | None = None) -> Item: ...

    def add_comment(self, item_id: str, comment: Comment, *, actor: dict[str, Any] | None = None) -> Item: ...

    def update_settings(self, settings: Settings) -> Settings: ...

    def create_access_request(self, payload: AccessRequest) -> AccessRequest: ...

    def reset_demo(self) -> AppData: ...
